// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grlnakfgjvhittqtkkbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdybG5ha2ZnanZoaXR0cXRra2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTI5MDYsImV4cCI6MjA3MzQyODkwNn0.DjBwKuHcplrQfC9YtH9vGABt_zeoRjaj8ql6in84rn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});